version: '3'

vars:
  TARGET_DIRS: ./scripts

tasks:
  default:
    deps: [all_for_ci, shellcheck, typo_check]

  all_for_ci:
    deps: [lint_node, lint_python]

  lint_python:
    deps: [ruff, yamllint, pytest]

  lint_node:
    deps: [markdownlint, pyright]

  pytest:
    cmds:
      - pytest -s

  yamllint:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
          -prune -o -type f -name '*.yml' -print \
        | xargs yamllint --no-warnings -c .yamllint.yml

  ruff:
    cmds:
      - ruff format --respect-gitignore --check
      - ruff check --respect-gitignore

  pyright:
    cmds:
      - npx pyright

  markdownlint:
    cmds:
      - >-
        find . -type d \( -name node_modules -o -name .venv \) \
          -prune -o -type f -name '*.md' -print \
        | xargs npx markdownlint --config ./.markdownlint.json

  shellcheck:
    cmds:
      - >-
        find {{ .TARGET_DIRS }} -type f \
          | grep \.sh$ | xargs shellcheck

  typo_check:
    cmds:
      - typos -V && typos
